### ISSUE TITLE
G450 (Vera Plus) & Dropbear

### ISSUE THREAD

**Issue by polskikrol** [toggledbits/Vera-Decouple#6]
```
# PLATFORM: NA301 on 5245, dropbear starts at 50
# PLATFORM: G450 on 5186, dropbear starts at 15 (before network at 20?)
# Start dropbear earlier, so we can debug other startup problems more easily.
if [ -L /etc/rc.d/S50dropbear ]; then
	sed -i 's/START=.*/START=21/' /etc/init.d/dropbear
	mv -f /etc/rc.d/S50dropbear /etc/rc.d/S21dropbear
fi
```

Does it make sense to add a case statement here of if condition for the following on G450?

`mv -f /etc/rc.d/S15dropbear /etc/rc.d/S21dropbear`

Otherwise, this will throw an error as /etc/rc.d/S50dropbear doesnt exist.

**Comment by toggledbits** [comment]
If S50dropbear doesn't exist it does nothing. That's the point of the conditional. What am I missing?

**Comment by polskikrol** [comment]
True! Missed that :/ Suppose I am thinking of the G450 corner case:

`if [ -L /etc/rc.d/S15dropbear ]; then
	sed -i 's/START=.*/START=21/' /etc/init.d/dropbear
	mv -f /etc/rc.d/S15dropbear /etc/rc.d/S21dropbear
fi`

**Comment by toggledbits** [comment]
The issue specifically for the Edge was the late start (50) of dropbear after other Vera-added init tasks; those tasks going wrong could leave you without SSH access to the system. 

I don't think the G450 startup order is a problem; I think it's OpenWrt's default order, in fact, and starting up before the network doesn't seem to be a problem for it, it recognizes when interfaces come up. Aside from a few storage/mount tasks, 15 is a good position relative to the remaining Vera tasks, so I'm not inclined to change it. Despite what you may think, I've tried to make these scripts do the absolute minimum necessary with the softest touch possible to accomplish the goal (sometimes achieved, sometimes just had to get rough).

This is another one of those situations where it's clear that the build for the Edge is very distinct from the Plus/Secure, something I've known for a while simple because the Lua libraries have been different. There are a number of other differences sprinkled throughout. I suspect I know how they got there. I have build environments now for OpenWrt for both mt7620a and mt7621 at the same versions Vera is using. My guess is that they branched a new source/build tree for the Edge in early development, to keep any necessary changes isolated, and never merged the two trees back together so they could just flip a switch/config to build one or the other (as I do). So over the years that source tree has diverged a bit from the Plus/Secure tree, and the further it has, the less incentive there has been to merge them back to sameness. I have lots of notes about the differences, which range from entirely different versions of same-named scripts to simply using a `.sh` suffix on a file on one system but not on the other. It keeps things exciting.

**Comment by polskikrol** [comment]
It has been a while since I have tinkered with busybox and dropbear on the Linksys WRT54G or SLUG devices. I wasnt inclined to make the dropbear startup script change on my Vera Plus in case I borked something and lost access without RS232 connectivity. Just wanted to make sure that for consistency and/or operational reasons, the corner case for G450 wasnt addressed via code. Sounds like it is not necessary as per your testing. Will mark this as closed. Thanks!
